#spring.datasource.url= jdbc:mysql://localhost:3310/springbootdemodb?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
## use validate for production
#spring.jpa.hibernate.ddl-auto= create-drop
#
#


spring:
  datasource:
    url: jdbc:mysql://localhost:3310/MyBookApi?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 8010

logging:
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 20MB
